<?php

namespace PS\ProjectBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getProjectWithParticipant(){
        $qb = $this->getEntityManager()->createQueryBuilder()

		
		    ->from('PSProjectBundle:Project', 'pro')
			->addSelect('pro')
			
			->leftJoin('pro.participants', 'par')
			 ->addSelect('par')


		;
		
		return $qb
		  ->getQuery()
		  ->getOneOrNullResult();
		;
	}
    
    
}
